server.host: "0.0.0.0"
server.basePath: "/kibana"

elasticsearch.username: "elastic"
elasticsearch.password: "UMApassWord123"
server.rewriteBasePath: true
elasticsearch.hosts: ["http://elasticsearch:9200"]
elasticsearch.ssl.verificationMode: none

#xpack.security.enabled: true
xpack.monitoring.collection.enabled: true
xpack.encryptedSavedObjects.encryptionKey: "b416fec37d010ff44c3736f3e5cef35db6298b441e81f28be99ab219f0e775e7"
xpack.security.encryptionKey: "b416fec37d010ff44c3736f3e5cef35db6298b441e81f28be99ab219f0e775e7"
xpack.reporting.encryptionKey: "5ec5dec1ada7818817ab33b9422dd217388e684721dad4940bb94762e84f53e0"

xpack.security.authc.providers:
  basic.basic1:
    order: 0
    enabled: true

xpack.security.session.idleTimeout: "8h"
xpack.security.session.lifespan: "30d"

monitoring.ui.container.elasticsearch.enabled: true